services:
    awakit.media.subscriber:
        class: Awakit\MediaBundle\Listener\MediaSubscriber
        arguments:
            - "@awakit.media.provider.factory"
        tags:
            - { name: doctrine.event_subscriber }