parameters:
    awakit.media.subscriber.class: Awakit\MediaBundle\Listener\MediaSubscriber

services:
    awakit.media.subscriber:
        class: "%awakit.media.subscriber.class%"
        arguments:
            - "@awakit.media.provider.factory"
        tags:
            - { name: doctrine.event_subscriber }