services:
    awakit.media.manager:
        class: Awakit\MediaBundle\Manager\MediaManager
        arguments: ["@doctrine.orm.entity_manager", 'AwakitMediaBundle:Media']
        
    awakit.media.subscriber:
        class: Awakit\MediaBundle\Listener\MediaSubscriber
        arguments:
            - "@awakit.media.provider.factory"
        tags:
            - { name: doctrine.event_subscriber }