parameters:
    awakit.media.twig.extension.class: Awakit\MediaBundle\Twig\Extension\MediaExtension

services:
    awakit.media.twig.extension:
        class: "%awakit.media.twig.extension.class%"
        arguments: [ "@awakit.media.provider.factory", "@twig", "@liip_imagine.cache.manager" ]
        tags:
            - { name: twig.extension }

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }